Update status-react quickstart and build-status
status-im/status.im pull request #580
Opened 2020-09-14 15:35 UTC by jinhojang6

1. Quick start

Update outdated instructions at https://status.im/technical/build_status/status_react_quickstart.html

- Replace `make startdev-ios-simulator` with `make run-clojure` (+ a screenshot)
- Replace `make react-native-ios` with `make run-metro` (+ a screenshot)
- Removed outdated screenshots
- Removed the `Debugging & Developing with re-frisk` section as `http://localhost:4567` doesn't work
- Replace `MacOS 10.15 “Catalina” or later` with `Nix`

Test link: https://dev-lang.status.im/technical/build_status/status_react_quickstart.html

2. Build Status
- Replace `Prompt will show when Figwheel connects to your application` with `Build completed` as I can find in the terminal.

Test link: https://dev-lang.status.im/technical/build_status/

2020-09-14 16:12 UTC, jakubgs commented on source/technical/build_status/status_react_quickstart.md
> +- [Nix](https://github.com/status-im/status-react/blob/develop/nix/README.md#macos-1015-catalina)
I'm not sure this change makes sense. The issue is related to Nix, yes, but only on MacOS 10.15 or higher, so the title was pretty accurate if you ask me. Maybe you could prefix it with `Nix on`.

2020-09-14 16:13 UTC, jakubgs requested changes
I see you remove some outdated screenshots from the markdown file, but not from the repo. Why?

2020-09-14 16:23 UTC, jinhojang6 commented on source/technical/build_status/status_react_quickstart.md
> +- [Nix](https://github.com/status-im/status-react/blob/develop/nix/README.md#macos-1015-catalina)
Didn't know that. Let me update it to `[Nix on MacOS 10.15 or higher](https://github.com/status-im/status-react/blob/develop/nix/README.md#macos-1015-catalina)`

2020-09-14 16:25 UTC, jinhojang6 commented
Thought it would be better to keep them as they could be used somewhere. Let me delete the outdated png files.

2020-09-15 14:21 UTC, jinhojang6 commented
@jakubgs Updated the commit based on your feedback. 

https://dev-lang.status.im/technical/build_status/status_react_quickstart.html

2020-09-15 16:18 UTC, jakubgs approved these changes
LGTM, thanks for fixing.

2020-09-15 16:18 UTC, merged