Split the Status Node guideline
status-im/status.im pull request #649
Opened 2021-06-15 16:04 UTC by jinhojang6

Split the Status Node guideline.

Tested at 
- https://dev-lang.status.im/technical/status_node_quick_start.html
- https://dev-lang.status.im/technical/deploy_ec2_instance.html

2021-06-15 16:11 UTC, jakubgs requested changes
Maybe we can add an `Other` or `Misc` sidebar section where the link to AWS EC2 setup guide can be added.

I'd also add a link to the quickstart guide at the beginning and end of the AWS EC2 guide.

2021-06-15 16:35 UTC, jinhojang6 commented
Updated the PR

2021-06-15 19:14 UTC, jakubgs commented on source/technical/others/deploy_ec2_instance.md
> +This guide will walk you through how to set up an Ubuntu machine to run a Status Node. Afterwards you can follow this [quickstart guide](../status_node_step_by_step.html) to configure the Status Node
This uses the "quickstart" word. Also, the folder is still called `status_node_quick_start`.

2021-06-15 19:15 UTC, jakubgs commented on source/technical/status_node_step_by_step.md
I'd add another final line here referencing the Step-by-Step guide again.

2021-06-15 19:15 UTC, jakubgs requested changes
Almost done, the folder for images has old name.

2021-06-16 12:44 UTC, jinhojang6 commented
@jakubgs Updated the PR excluding the comment `I'd add another final line here referencing the Step-by-Step guide again.`

2021-06-16 13:59 UTC, jinhojang6 commented
Added `If you successfully deployed an EC2 instance, please follow this [Status Node Step-by-Step guide](../status_node_step_by_step.html) to configure a Status Node.` on `deploy_ec2_instance.md`

2021-06-16 14:01 UTC, jakubgs approved these changes

2021-06-16 14:01 UTC, merged