Status node runners page
status-im/status.im pull request #658
Opened 2021-07-26 14:26 UTC by ClumsyVlad

2021-07-26 15:10 UTC, jakubgs commented on themes/navy/layout/snr.ejs
> +		}
Please don't add custom CSS. You can modify the Tailwind CSS by adding custom rules in `tailwind.config.js`:
```js
 // tailwind.config.js
  module.exports = {
    theme: {
      minHeight: {
       '0': '0',
       '1/4': '25%',
       '1/2': '50%',
       '3/4': '75%',
       'full': '100%',
      }
    }
  }
```
https://tailwindcss.com/docs/min-height#customizing

2021-07-26 15:11 UTC, jakubgs commented on themes/navy/layout/snr.ejs
> +		}
There is already an example for `maxHeight`:
https://github.com/status-im/status.im/blob/423d95b03f077e2704d6173167ade232ad6918bf/tailwind.config.js#L137-L140

2021-07-26 15:14 UTC, jakubgs commented on themes/navy/layout/snr.ejs
> +		}
There are screen sizes that you can add too, but it's better to use already available ones if possible:
https://github.com/status-im/status.im/blob/423d95b03f077e2704d6173167ade232ad6918bf/tailwind.config.js#L34-L43

2021-07-26 15:15 UTC, jakubgs commented on source/_data/nightlies.yml
> +SHA: 'https://status-im-nightlies.ams3.digitaloceanspaces.com/StatusIm-210723-055900-170ef0-nightly.sha256'
You don't need to commit changes in this file.

2021-07-26 15:17 UTC, jakubgs reviewed
It's looking good so far. Are we sure `snr` is a good name for this? I'd expect `snp` since it's Status Node Program, but what do I know. @j-zerah thoughts?

Also, are we sure we want to add an link in the main navigation bar in the header?
Just big `SNR` doesn't really mean anything, and full `Node Program` would take up considerable space, unless this is just a placeholder.

I've deployed a test instance here, but might be slow: https://892ede541451.eu.ngrok.io/snr/

2021-07-26 15:41 UTC, j-zerah commented
@jakubgs SNR is placeholder and there should NOT be a link to it in the global navigation. I have no clue what SNR means.

Lets use the domain - https://status.im/status-nodes

2021-07-27 10:39 UTC, jakubgs requested changes
Looks good, but three things:

1. We don't want the header navigation addition.
2. Could you move all `img` assets into a `status-nodes` subfolder?
3. Please squash all changes into one commit.

Thanks.

2021-07-27 10:39 UTC, jakubgs commented on themes/navy/layout/partial/header.ejs
> +            <li class="hover:text-primary-base py-4 border-t border-gray-100 md:text-lg 2xl:text-xl xl:border-t-0 xl:px-4 2xl:px-8 xl:py-16 <% if(is_current('snr')) { %>active<% } %>"><a href="<%- sh
Pretty sure we don't want this.

2021-07-29 11:13 UTC, jakubgs approved these changes
```
themes/navy/source/img/status-nodes/status-nodes-cloud.png
```
I really don't think all the images need the `status-nodes-` prefix if they are already in the `status-nodes` folder, makes the filenames unnecessarily long. But that's just a nitpick.

Another nitpick are the SVG icons embedded in the HTML directly.

Other than that looks good. Built it locally, see no major issues.

2021-07-29 11:13 UTC, jakubgs commented on themes/navy/layout/status-nodes.ejs
> +								<path opacity="1" fill-rule="evenodd" clip-rule="evenodd"
Why is this SVG directly embedded in the HTML? Any reason why you can't just use `<%- image_tag('/img/icon-arrow-right-black.svg') %>`?

2021-07-29 11:13 UTC, jakubgs commented on themes/navy/layout/status-nodes.ejs
> +									<path opacity="1" fill-rule="evenodd" clip-rule="evenodd"
Same here, why not reuse an existing SVG asset?

2021-07-29 11:13 UTC, jakubgs commented on themes/navy/layout/status-nodes.ejs
> +								<path opacity="1" fill-rule="evenodd" clip-rule="evenodd"
And here.

2021-07-29 11:55 UTC, ClumsyVlad commented on themes/navy/layout/status-nodes.ejs
> +								<path opacity="1" fill-rule="evenodd" clip-rule="evenodd"
You have buttons that change the background and text color on: hover. SVG embedded in HTML changes color just like text inside a button. On the contrary, I would use inline SVG so that when: hover the arrow in the button does not merge with the background of the button. What do you think?

2021-07-29 12:18 UTC, jakubgs commented on themes/navy/layout/status-nodes.ejs
> +								<path opacity="1" fill-rule="evenodd" clip-rule="evenodd"
I see, that makes sense.

2021-07-29 12:20 UTC, jakubgs commented on source/influencer-guidelines/index.md
> +layout: influencer-guidelines
That's weird. Why is this change here?

2021-07-29 12:21 UTC, jakubgs commented on source/influencer-guidelines/index.md
> +layout: influencer-guidelines
Maybe some rebasing mistake? I also see a change to `source/_data/nightlies.yml`.

2021-07-29 12:58 UTC, ClumsyVlad commented on source/influencer-guidelines/index.md
> +layout: influencer-guidelines
Yeah, that was rebasing mistake, just grabbed one extra commit, sorry for that.

2021-07-29 13:16 UTC, jakubgs approved these changes
LGTM

2021-07-29 13:17 UTC, jakubgs commented on source/influencer-guidelines/index.md
> +layout: influencer-guidelines
Cool. Thanks.

2021-07-29 13:17 UTC, jakubgs commented
I'll merge this and sign it myself afterwards, but I recommend setting up GPG for commit signing:
https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/signing-commits

2021-07-29 13:17 UTC, merged

2021-07-29 13:21 UTC, jakubgs commented
@j-zerah does this look good to you?
https://dev.status.im/status-nodes/

2021-07-29 14:01 UTC, j-zerah commented
@jakubgs this looks good. But please note, we will need to update all the links next week once we have all finalized:

- Application form
- Video (with youtube link)
- What is a Node (learn more - to blog posts)
- Status channel (#status-node-runners)