Scroll & unfold a FAQ item by ID
status-im/status.im pull request #684
Opened 2021-11-29 21:30 UTC by jinhojang6

Assign IDs to the FAQ items

Test:

1) yarn devel
2) visit http://localhost:8080/faq/#site-faq-general-q12-questio

Desktop
<img width="1624" alt="Screen Shot 2021-11-30 at 6 28 53 AM" src="https://user-images.githubusercontent.com/41753422/143945686-3776284b-83db-4bc6-93bd-448459f7d32b.png">

Mobile
<img width="423" alt="Screen Shot 2021-11-30 at 6 29 12 AM" src="https://user-images.githubusercontent.com/41753422/143945727-7e43f7a5-4dc7-4d20-b3b5-92f9e099e777.png">

2021-11-30 00:44 UTC, jakubgs requested changes
We want the IDs to be human readable, so instead of using the question ID we should use the question text itself,but we have to clean it up a bit.:
```js
__(entry.question).replace(/[^\w]/g, '-').replace(/-$/, '').toLowerCase()
```
We use  `[^\w]` to represent non-word characters, I'm also removing trailing dash caused by question mark. And since EJS just embeds JavaScript in HTML for templating engine we can just set this as a variable:
```ejs
<% const hash = __(entry.question).replace(/[^\w]/g, '-').replace(/-$/, '').toLowerCase() %>
```
We don't need the hash at the beginning because it can cause query issues:
```ejs
<div id="<%= hash %>" class="accordion bg-primary-100 mt-12 p-6">
```
We can use the same `hash` variable in other places, like the `a` tag:
```ejs
<a href="#" data-toggle="collapse" data-target="#<%= hash %>-answer" aria-expanded="false" aria-controls="<%= hash %>">
```
```ejs
<div id="<%= hash %>-answer" class="mt-8 hidden text-gray-500 collapse accordion-content">
    <div class="description"><%- __(entry.answer) %></div>
</div>
```
Notice that I'm appending `-answer` to the `id` of the `div` with the answer and to the `data-target` so the accordion can be opened/collapsed using the `a` tag. I omitted the `class` attribute from `a` tag only for brevity.

Now we can do something like this:
```js
const hash = window.location.hash.substring(1);
$(`div#${hash}>a`).click();
setTimeout(() => {
  const yOffset = -100;
  const element = document.getElementById(hash);
  const y = element.getBoundingClientRect().top + window.pageYOffset + yOffset;
  window.scrollTo({ top: y, behavior: 'smooth' });
}, 400);
```
But one thing is still missing. We need to update `window.location.hash` when someone click to unfold a question.

2021-11-30 15:06 UTC, jinhojang6 commented
@jakubgs 

Updated it including the update for `window.location.hash`. But `$(`div#${hash}>a`).click();` didn't work so used `const answer = $(`a[data-target="#${hash}"]`);` instead.

2021-11-30 15:58 UTC, jakubgs commented on themes/navy/source/js/main.js
> +  if (document.title === 'Status - FAQ' && window.location.hash.length) {
I think checking path is better than checking title.
```suggestion
  if (window.location.pathname === '/faq/') {
```
Also, we don't want to depend on the hash being set if we are also handling clicks.

2021-11-30 15:59 UTC, jakubgs commented on themes/navy/source/js/main.js
> +    answer.on("click", () => {
This is incorrect. We don't want to handle the click on the link that we opened the page to, but any link. So we want something like this:
```js
$('a.custom-accordion-trigger').click((ev) =>
  history.pushState({}, "", `/faq/${$(ev.target).data("target")}`)
})
```

2021-11-30 16:00 UTC, jakubgs commented on themes/navy/source/js/main.js
> +    answer.on("click", () => {
Although adding a custom class like `question-link` would probably be better.

2021-11-30 16:02 UTC, jakubgs commented on themes/navy/source/js/main.js
> +    answer.click();
We want to move the clicking of the link from the hash and scrolling into its own `if`:
```js
    const hash = window.location.hash.substring(1);
    if (hash.length) {
      $(`a[data-target="#${hash}"]`).click();
      setTimeout(() => {
        const yOffset = w < 768 ? -150 : -190;
        const element = document.getElementById(hash);
        const y = element.getBoundingClientRect().top + window.pageYOffset + yOffset;
        window.scrollTo({ top: y, behavior: 'smooth' });
      }, 400);
    }
```

2021-11-30 16:03 UTC, jakubgs commented on themes/navy/layout/faq.ejs
> +                        <a href="#" class="text-2xl collapsed flex items-center justify-between custom-accordion-trigger" data-toggle="collapse" data-target="#<%= hash %>-answer" aria-expanded="false
I think adding an `id` without `-answer` would make for a cleaner link. The `div` with the `answer` should have and `id` with `-answer` added, but the `a` link with the question should __not__ have `-answer` at the end of the ID. This way we get shorter IDs for the URL hash.

2021-11-30 16:15 UTC, jakubgs commented on themes/navy/source/js/main.js
> +    answer.on("click", () => {
We could also set the second argument to `$(ev.target).text()`, even if many browsers don't support it.

Or even better: `FAQ: ${$(ev.target).test()}`

2021-12-01 16:27 UTC, jinhojang6 commented
Updated the PR. Misunderstood some stuff regarding the unfolding.

Tested at : http://localhost:8080/faq/#are-there-any-fees-answer

2021-12-01 16:30 UTC, jakubgs commented on themes/navy/source/js/main.js
> +      })
Because it's withing the `if (hash.length)` block it will only work when URL was opened with a hash argument in place.

2021-12-01 16:31 UTC, jakubgs commented on themes/navy/source/js/main.js
> +      })
And you are still using the ID with `-answer`, which us unnecessary.

2021-12-01 16:47 UTC, jakubgs approved these changes
Ok, now we have both clicking and scrolling to answer.

I guess we can leave the color change for later if this is not enough.

2021-12-01 16:48 UTC, merged